import pandas as pd
from pathlib import Path


# read sample assignment table
#sample_df = pd.read_csv(config['SAMPLE_TABLE'], sep='\t')
FLOW_CELLS = ['PBEH1_1', 'PBEH1_2']
PLASMIDS = [
	f.stem for f in Path('../resources/referenceDNA/genbank').iterdir()
	]
NUM_DIVS = 100
DIVS = [i for i in range(1, NUM_DIVS+1)]


include: 'rules/fastQC.smk'
include: 'rules/debarcode.smk'
include: 'rules/footloop.smk'
include: 'rules/multiqc.smk'
include: 'rules/identifyPlasmids.smk'

FLOW_CELLS = ['PBEH1_1', 'PBEH1_2']
# PLASMIDS = [
# 	f.stem for f in Path('/home/ethollem/projects/PBEH1/resources/referenceDNA/genbank').iterdir()
# 	]
NUM_DIVS = 100
DIVS = [i for i in range(1, NUM_DIVS+1)]


rule all:
    input:
        expand(
                'output/plots/peaks/{flow_cell}/',
                flow_cell=FLOW_CELLS
            )